
# Project information
site_name: Causal Inference (causalinf)
site_url: https://www.diogoferrari.com/causalinf
repo_url: https://github.com/DiogoFerrari/causalinf
repo_name: causalinf
use_directory_urls: true

nav:
  - Overview: index.md
  - Usage:
    - <font color="#a41034">Installation</font>: usage/installation.md
    - <font color="#a41034">Import</font>: usage/import.md
    - <font color="#a41034">Basic Functions</font>: 
      - Overview: usage/overview.md
      - Model Assumptions: usage/assumptions.md
      - Estimation: usage/estimation.md
      - Summary and reporting: usage/summary-and-reporting.md
      - Sensitivity Analysis: usage/sensitivity.md
      - Examples: usage/examples.md
      - Simulate Data: usage/simulate-data.md
  - Methods:
    # - <font color="#a41034">GCM (Graphical Causal Models)</font>:
    - <font color="#a41034">GCM</font>:
      - Introduction: methods/gcm/introduction.md
      - Build: methods/gcm/build.md
      - Visualize: methods/gcm/plot.md
      - Check Assumptions: methods/gcm/assumptions.md
      - Identification Analysis: methods/gcm/identification.md
    # - <font color="#a41034">SCM (Structural Causal Models)</font>: methods/scm.md
    - <font color="#a41034">SCM</font>: methods/scm.md
      # - Assumptions: methods/scm/assumptions.md
      # - Estimate: methods/scm/estimate.md
      # - Report: methods/scm/report.md
    # - <font color="#a41034">CBN (Causal Bayesian Networds)</font>: methods/cbn.md
    - <font color="#a41034">CBN</font>: methods/cbn.md
      # - Assumptions: methods/cbn/assumptions.md
      # - Estimate: methods/cbn/estimate.md
      # - Report: methods/cbn/report.md
    # - <font color="#a41034">SoO (Selection on Observables)</font>:
    - <font color="#a41034">SoO</font>:
      - Estimate: methods/soo/estimate.md
      - Report: methods/soo/report.md
    # - <font color="#a41034">DiD (Difference-in-Differences)</font>:
    - <font color="#a41034">DiD</font>:
      - Estimate: methods/did/estimate.md
      - Report: methods/did/report.md
    # - <font color="#a41034">IV (Instrumental Variables)</font>:
    - <font color="#a41034">IV</font>:
      - Estimate: methods/iv/estimate.md
      - Report: methods/iv/report.md
    # - <font color="#a41034"> RD (Regression discontinuity)</font>:
    - <font color="#a41034"> RD</font>:
      - Estimate: methods/rd/estimate.md
      - Report: methods/rd/report.md
  - Case Studies:
    - <font color="#a41034">DiD</font>:
      - Minimal Wage Effect: case-studies/did-card1994minimum.md
  - API Reference: api.md
  - Releases: releases.md

theme:
  name: material
  locale: en
  custom_dir: docs/_css
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: white
    primary: custom
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  logo: _css/causalinf-icon.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - toc.integrate  # combine right ToC into the left ToC
    - toc.follow
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    # - navigation.expand # start headings expanded
    # - navigation.sections # if used, won't collapse the headings of right-side menu
    - navigation.prune # fold the headings on the right-side that are not the focus
    - navigation.tracking
    - navigation.instant
    # - navigation.footer
    - navigation.indexes


# Preview controls
strict: true


extra_css:
  - _css/extra.css
  - _css/stylesheets.css

plugins:
  - search
  - charts
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_signature: true
            docstring_style: numpy
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: false
            show_object_full_path: true

markdown_extensions:
  - admonition
  - attr_list
  - extra
  - tables
  - mdx_math:
      enable_dollar_delimiter: True
  - fenced_code
  - smarty
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  # - pymdownx.superfences
  # - pymdownx.tabbed:
  #     alternate_style: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - toc:
      # permalink: true  # Adds a permalink icon to each heading
      # permalink_title: Anchor link to this section for reference
      # title: On this page # Custom title for the TOC
      toc_depth: 4

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
