# Project information
site_name: Causal Inference (causalinf)
site_url: https://www.diogoferrari.com/causalinf
repo_url: https://github.com/DiogoFerrari/causalinf
repo_name: causalinf
use_directory_urls: true

nav:
  - Overview: index.md
  - Usage:
    - <font color="#a41034">Installation</font>: usage/installation.md
    - <font color="#a41034">Import</font>: usage/import.md
    - <font color="#a41034">Core Functions</font>: usage/overview.md
    - <font color="#a41034">Model Assumptions</font>: usage/assumptions.md
    - <font color="#a41034">Estimation</font>: usage/estimation.md
    - <font color="#a41034">Summary and Reporting</font>: usage/summary-and-reporting.md
    - <font color="#a41034">Sensitivity Analysis</font>: usage/sensitivity.md
    - <font color="#a41034">Examples</font>: usage/examples.md
    - <font color="#a41034">Simulate Data</font>: usage/simulate-data.md
  - Methods:
    - Overview: methods/overview.md
    - <font color="#a41034">Graphical Causal Models (GCM)</font>:
      - Introduction: methods/gcm/introduction.md
      - Build: methods/gcm/build.md
      - Visualize: methods/gcm/plot.md
      - Check Assumptions: methods/gcm/assumptions.md
      - Identification Analysis: methods/gcm/identification.md
    - <font color="#a41034">Structural Causal Models (SCM)</font>: methods/scm.md
      # - Assumptions: methods/scm/assumptions.md
      # - Estimate: methods/scm/estimate.md
      # - Report: methods/scm/report.md
    - <font color="#a41034">Causal Bayesian Networds (CBN)</font>: methods/cbn.md
      # - Assumptions: methods/cbn/assumptions.md
      # - Estimate: methods/cbn/estimate.md
      # - Report: methods/cbn/report.md
    - <font color="#a41034">Selection on Observables (SoO)</font>:
      - Estimate: methods/soo/estimate.md
      - Report: methods/soo/report.md
    - <font color="#a41034">Difference-in-Differences (DiD)</font>:
      - Estimate: methods/did/estimate.md
      - Report: methods/did/report.md
    - <font color="#a41034">Instrumental Variable (IV)</font>:
      - Estimate: methods/iv/estimate.md
      - Report: methods/iv/report.md
    - <font color="#a41034">Regression Discontinuity (RD)</font>:
      - Estimate: methods/rd/estimate.md
      - Report: methods/rd/report.md
  - Case Studies:
    - Overview: case-studies/overview.md
    - <font color="#a41034">DiD</font>:
      - Minimal Wage Effect: case-studies/did-card1994minimum.md
  ## - API Reference: api.md ## <- usual API
  - API reference: reference/ ## using py to create one docstring per page
  - Releases: releases.md

theme:
  name: material
  locale: en
  custom_dir: docs/_css
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: white
    primary: custom
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  logo: _css/causalinf-icon.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - toc.integrate  # combine right ToC into the left ToC
    - toc.follow
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    # - navigation.expand # start headings expanded
    # - navigation.sections # if used, won't collapse the headings of right-side menu
    - navigation.prune # fold the headings on the right-side that are not the focus
    - navigation.tracking
    - navigation.instant
    # - navigation.footer
    - navigation.indexes


# Preview controls
strict: false


extra_css:
  - _css/extra.css
  - _css/stylesheets.css

plugins:
  - search
  - charts
  - mkdocstrings:
      handlers:
        python:
          paths: ["causalinf"] # <-- for the API docstring using .py (per page docstring)
          options:
            show_source: true
            show_signature: true
            docstring_style: numpy
            docstring_options:
              warn_unknown_params: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: false
            show_object_full_path: true
  - section-index
  - autolinks 
  # starting here for one docstring per page
  - gen-files:
      scripts:
        - docs/src/gen_ref_pages.py  
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - admonition
  - attr_list
  - extra
  - tables
  - mdx_math:
      enable_dollar_delimiter: True
  - fenced_code
  - smarty
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      default_lang: python
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
        generic: true
  # - pymdownx.superfences
  # - pymdownx.tabbed:
  #     alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - toc:
      # permalink: true  # Adds a permalink icon to each heading
      # permalink_title: Anchor link to this section for reference
      # title: On this page # Custom title for the TOC
      toc_depth: 4
  # for latex tables

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # 1. Load Config FIRST
  - src/mathjax.js

  # 2. Load Vega (Charts)
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

  # 3. Load MathJax Library LAST
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js